name: Сборка APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Получить код
        uses: actions/checkout@v5

      - name: Установить Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'

      - name: Настроить Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          gradle-version: '8.10'

      - name: Собрать APK
        run: gradle assembleDebug

      - name: Сохранить APK
        uses: actions/upload-artifact@v4
        with:
          name: RunApp-APK
          path: app/build/outputs/apk/debug/app-debug.apk
